import dash
from dash import html, dcc, callback, Output, Input, State
import plotly.graph_objects as go

dash.register_page(__name__, path="/form-generation", name="Form Generation", title="Form Generation – ADV & PF")

year_options = [
    {"label": "2024", "value": "2024"},
    {"label": "2023", "value": "2023"},
    {"label": "2022", "value": "2022"},
]

adv_section_options = [
    {"label": "All", "value": "All"},
    {"label": "Section 1", "value": "Section 1"},
    {"label": "Section 2", "value": "Section 2"},
    {"label": "Section 5", "value": "Section 5"},
    {"label": "Section 7", "value": "Section 7"},
    {"label": "Schedule D", "value": "Schedule D"},
]

pf_section_options = [
    {"label": "All", "value": "All"},
    {"label": "Section A", "value": "Section A"},
    {"label": "Section B", "value": "Section B"},
    {"label": "Section C", "value": "Section C"},
    {"label": "Schedule", "value": "Schedule"},
]

adv_history_rows = [
    {"version": "v1.2", "generated_on": "Aug 18, 2024 11:00 AM", "generated_by": "S. Rahman", "status": "Ready for Review", "status_badge": "badge-success", "actions": ["Download", "Preview", "View Audit"]},
    {"version": "v1.1", "generated_on": "Aug 15, 2024 02:30 PM", "generated_by": "S. Rahman", "status": "Superseded", "status_badge": "badge-muted", "actions": ["View Audit"]},
    {"version": "v1.0", "generated_on": "Aug 10, 2024 09:00 AM", "generated_by": "System", "status": "Superseded", "status_badge": "badge-muted", "actions": ["View Audit"]},
]

pf_history_rows = [
    {"version": "v2.1", "generated_on": "Aug 20, 2024 02:00 PM", "generated_by": "Tax Ops", "status": "Exceptions Flagged", "status_badge": "badge-warning", "actions": ["Download", "Preview", "View Audit"]},
    {"version": "v2.0", "generated_on": "Aug 17, 2024 10:00 AM", "generated_by": "S. Rahman", "status": "Superseded", "status_badge": "badge-muted", "actions": ["View Audit"]},
]


def make_generation_history_table(rows):
    header = html.Tr([
        html.Th("Version"),
        html.Th("Generated On"),
        html.Th("Generated By"),
        html.Th("Status"),
        html.Th("Actions"),
    ])
    table_rows = []
    for r in rows:
        action_links = []
        for i, action in enumerate(r["actions"]):
            if i > 0:
                action_links.append(html.Span(" ", style={"margin": "0 2px"}))
            action_links.append(html.A(action, href="#", className="action-link"))
        table_rows.append(
            html.Tr([
                html.Td(r["version"], className="cell-primary"),
                html.Td(r["generated_on"]),
                html.Td(r["generated_by"]),
                html.Td(html.Span(r["status"], className=f"status-badge {r['status_badge']}")),
                html.Td(action_links),
            ])
        )
    return html.Div(
        html.Table(
            [html.Thead(header), html.Tbody(table_rows)],
            className="data-table",
        ),
        className="data-table-wrap",
    )


def make_adv_tab():
    generate_panel = html.Div(
        [
            html.Div(
                [
                    html.Div(
                        [
                            html.Span("Last Generated:", className="text-muted", style={"fontSize": "13px"}),
                            html.Span(" Aug 18, 2024 11:00 AM", style={"color": "#111827", "fontSize": "13px", "marginLeft": "6px"}),
                        ],
                        style={"marginBottom": "6px"},
                    ),
                    html.Div(
                        [
                            html.Span("Generated By:", className="text-muted", style={"fontSize": "13px"}),
                            html.Span(" S. Rahman", style={"color": "#111827", "fontSize": "13px", "marginLeft": "6px"}),
                        ],
                        style={"marginBottom": "6px"},
                    ),
                    html.Div(
                        [
                            html.Span("Status:", className="text-muted", style={"fontSize": "13px"}),
                            html.Span(" ", style={"marginLeft": "6px"}),
                            html.Span("Ready for Review", className="status-badge badge-success"),
                        ],
                        style={"marginBottom": "6px"},
                    ),
                ]
            ),
            html.Hr(className="divider"),
            html.Button(
                "Generate Filing-Ready ADV Workbook",
                className="btn btn-primary",
                style={"width": "100%", "marginBottom": "8px"},
            ),
            html.Button(
                "Preview ADV Workbook",
                className="btn",
                style={"width": "100%"},
            ),
            html.Div(
                "Generation is performed by a Databricks Job. Only reviewed/approved metrics are included.",
                className="text-muted",
                style={"fontSize": "12px", "marginTop": "8px"},
            ),
        ],
        className="panel-card",
    )

    history_panel = html.Div(
        [
            html.Div("ADV Generation History", className="panel-title"),
            make_generation_history_table(adv_history_rows),
        ],
        className="panel-card",
    )

    return html.Div(
        [
            html.Div("ADV Generation", className="section-title", style={"marginBottom": "12px"}),
            html.Div(
                [
                    html.Span("Filing Year", className="filter-label"),
                    dcc.Dropdown(
                        options=year_options,
                        value="2024",
                        clearable=False,
                        style={"minWidth": "120px"},
                    ),
                    html.Span("ADV Section", className="filter-label", style={"marginLeft": "16px"}),
                    dcc.Dropdown(
                        options=adv_section_options,
                        value="All",
                        clearable=False,
                        style={"minWidth": "180px"},
                    ),
                ],
                className="filter-bar",
                style={
                    "background": "transparent",
                    "border": "none",
                    "padding": "0",
                    "marginBottom": "16px",
                    "display": "flex",
                    "alignItems": "center",
                    "gap": "8px",
                },
            ),
            html.Div(
                [generate_panel, history_panel],
                className="grid-2",
            ),
        ]
    )


def make_pf_tab():
    generate_panel = html.Div(
        [
            html.Div(
                [
                    html.Div(
                        [
                            html.Span("Last Generated:", className="text-muted", style={"fontSize": "13px"}),
                            html.Span(" Aug 20, 2024 02:00 PM", style={"color": "#111827", "fontSize": "13px", "marginLeft": "6px"}),
                        ],
                        style={"marginBottom": "6px"},
                    ),
                    html.Div(
                        [
                            html.Span("Generated By:", className="text-muted", style={"fontSize": "13px"}),
                            html.Span(" Tax Ops", style={"color": "#111827", "fontSize": "13px", "marginLeft": "6px"}),
                        ],
                        style={"marginBottom": "6px"},
                    ),
                    html.Div(
                        [
                            html.Span("Status:", className="text-muted", style={"fontSize": "13px"}),
                            html.Span(" ", style={"marginLeft": "6px"}),
                            html.Span("Exceptions Flagged", className="status-badge badge-warning"),
                        ],
                        style={"marginBottom": "6px"},
                    ),
                ]
            ),
            html.Hr(className="divider"),
            html.Button(
                "Generate Filing-Ready PF Workbook",
                className="btn btn-primary",
                style={"width": "100%", "marginBottom": "8px"},
            ),
            html.Button(
                "Preview PF Workbook",
                className="btn",
                style={"width": "100%"},
            ),
            html.Div(
                "Generation is performed by a Databricks Job. Only reviewed/approved metrics are included.",
                className="text-muted",
                style={"fontSize": "12px", "marginTop": "8px"},
            ),
        ],
        className="panel-card",
    )

    history_panel = html.Div(
        [
            html.Div("PF Generation History", className="panel-title"),
            make_generation_history_table(pf_history_rows),
        ],
        className="panel-card",
    )

    return html.Div(
        [
            html.Div("PF Generation", className="section-title", style={"marginBottom": "12px"}),
            html.Div(
                [
                    html.Span("Filing Year", className="filter-label"),
                    dcc.Dropdown(
                        options=year_options,
                        value="2024",
                        clearable=False,
                        style={"minWidth": "120px"},
                    ),
                    html.Span("PF Section", className="filter-label", style={"marginLeft": "16px"}),
                    dcc.Dropdown(
                        options=pf_section_options,
                        value="All",
                        clearable=False,
                        style={"minWidth": "180px"},
                    ),
                ],
                className="filter-bar",
                style={
                    "background": "transparent",
                    "border": "none",
                    "padding": "0",
                    "marginBottom": "16px",
                    "display": "flex",
                    "alignItems": "center",
                    "gap": "8px",
                },
            ),
            html.Div(
                [generate_panel, history_panel],
                className="grid-2",
            ),
        ]
    )


layout = html.Div(
    [
        dcc.Store(id="gen-tab", data="ADV"),
        html.Div(
            [
                html.Div(
                    [
                        html.H1("Form Generation – ADV & PF", className="page-heading"),
                        html.Div(
                            "Generate filing-ready workbooks for ADV and PF submissions. ADV and PF are generated independently.",
                            className="page-subheading",
                        ),
                    ]
                ),
            ],
            className="page-header",
        ),
        html.Div(
            [
                html.Div(
                    [
                        html.Span(
                            "5 exceptions remain unresolved. Form generation is available but flagged. Resolve exceptions before final submission.",
                            className="notif-text",
                        ),
                    ],
                    className="notification-banner",
                    style={"marginBottom": "20px"},
                ),
            ]
        ),
        html.Div(
            [
                html.Div(
                    [
                        html.Div(
                            "ADV",
                            id="tab-adv",
                            className="tab-item tab-active",
                            n_clicks=0,
                        ),
                        html.Div(
                            "PF",
                            id="tab-pf",
                            className="tab-item",
                            n_clicks=0,
                        ),
                    ],
                    className="tab-bar",
                    style={"marginBottom": "20px"},
                ),
            ]
        ),
        html.Div(id="gen-tab-content"),
    ]
)


@callback(
    Output("gen-tab", "data"),
    Output("tab-adv", "className"),
    Output("tab-pf", "className"),
    Input("tab-adv", "n_clicks"),
    Input("tab-pf", "n_clicks"),
    State("gen-tab", "data"),
    prevent_initial_call=True,
)
def switch_tab(adv_clicks, pf_clicks, current_tab):
    from dash import ctx
    triggered = ctx.triggered_id
    if triggered == "tab-adv":
        return "ADV", "tab-item tab-active", "tab-item"
    elif triggered == "tab-pf":
        return "PF", "tab-item", "tab-item tab-active"
    return current_tab, "tab-item tab-active", "tab-item"


@callback(
    Output("gen-tab-content", "children"),
    Input("gen-tab", "data"),
)
def render_tab_content(tab):
    if tab == "PF":
        return make_pf_tab()
    return make_adv_tab()
